### ISSUE TITLE
AS7262 firmware > AT25SF041 Chip Size

### ISSUE THREAD

**Issue by eighthree** [sparkfun/Qwiic_Spectral_Sensor_AS726X#2]
Hi folks, The firmware provided for the AS7262 can't fit on an AT25SF041. Flashrom complains the image is > Chip size.
Could the file be updated with a 512k version>
Using flashrom on Raspbian Stretch

**Comment by nseidle** [comment]
Hi - It fits, you just have to trim it. The binary file has a large number of empty bytes starting around 0x43E40 (byte 278,080). 

![image](https://user-images.githubusercontent.com/117102/47620881-6b5d1c00-dab5-11e8-9745-5cf4d2bf8b22.png)

The windows CH341 software throws a similar error. I ignore it because the AMS core firmware ends at ~278k.
